ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "plan" TEXT NOT NULL DEFAULT 'FREE';
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "razorpay_customer_id" TEXT;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "razorpay_subscription_id" TEXT;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "plan_expires_at" TIMESTAMPTZ;
